import "material-symbols";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import Provider from "./context/Provider";
import type { ReactNode } from "./helpers/Types";
import "./styles/global.css";

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ReactNode) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
